### ISSUE TITLE
Date formats like '16 May 17'

### ISSUE THREAD

**Issue by akki2825** [wit-ai/duckling_old#241]
Date formats like '16 May 17' gets parsed as 'May 17' and '16 May'. On the other hand, what I meant was 16th May, 2017. Though I added a new rule without the ordinal for the date, the parsing result is the same as above. Is there a way to fix this? 
Thanks.

**Comment by justinas-vd** [comment]
As a human, I would be momentarily stumped if I saw '16 May 17'. Personally, I think that there is nothing to fix as in this particular case it's -- pardon my French -- shit in, shit out.
